local harpoon = require "harpoon"

harpoon:setup()

vim.keymap.set("n", "<leader>hh", function()
  harpoon:list():add()
end, { desc = "Add file to harpoon" })
vim.keymap.set("n", "<leader>h", function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Open harpoon ui with telescope" })

vim.keymap.set("n", "<leader>n", function()
  harpoon:list():select(1)
end, { desc = "Navigate to harpoon file 1" })
vim.keymap.set("n", "<leader>m", function()
  harpoon:list():select(2)
end, { desc = "Navigate to harpoon file 2" })
vim.keymap.set("n", "<leader>,", function()
  harpoon:list():select(3)
end, { desc = "Navigate to harpoon file 3" })
vim.keymap.set("n", "<leader>.", function()
  harpoon:list():select(4)
end, { desc = "Navigate to harpoon file 4" })
vim.keymap.set("n", "<leader>;", function()
  harpoon:list():select(5)
end, { desc = "Navigate to harpoon file 5" })
